# Generated by Django 3.2.7 on 2021-10-10 10:56

import ImageUpload.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(help_text='Max 50 characters', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Max 50 characters', max_length=50)),
                ('img_file', models.ImageField(max_length=250, upload_to=ImageUpload.models.user_directory_path)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('img_thumb', models.ImageField(blank=True, max_length=250, upload_to='media/')),
                ('img_s', models.ImageField(blank=True, max_length=250, upload_to='media/')),
                ('img_m', models.ImageField(blank=True, max_length=250, upload_to='media/')),
                ('img_l', models.ImageField(blank=True, max_length=250, upload_to='media/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageUpload.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
